### ISSUE TITLE
Group Review

### ISSUE THREAD

**Issue by planetorium** [double-double/web-app#19]
We completed many tasks to contribute to the UX portion of the project. We now have personas, sketches of our web app for both mobile and desktop, a working logo and colour palette for the project.

**Comment by planetorium** [comment]
I found it positive because it was helpful to check out the list that we had created and be able to check it off as I progressed on my tasks. I ended up finishing all of the tasks I set out to complete and was able to talk to the team about it in class.

I was not able to complete a couple of the tasks on one issue because it needs a bit more attention from the entire team together. We weren't exactly sure what direction we wanted to go with the writing, so this week we will be working with that again and bouncing ideas for text off of each other. We moved this issue to Sprint 3 to continue.

**Comment by krystyna-Macleod** [comment]
I feel it was a very positive week. I really like having the project and sprints in GitHub because it kept me updated on my task. I finish the task of completing the logo and have it ready to use in the web app. Also, I made some buttons but realizing that we might not need them after looking at the wireframe but we have them if needed.

**Comment by sungwoonjeong** [comment]
Overall the sprint was success. By creating a list of to-do list help me finish the assignment without getting confused. I was able to complete the wireframe over the weekend. After discussing with the group, we were able to create final wireframe.

**Comment by planetorium** [comment]
From Tamara:

I feel this week went well over all, the team was focused and completed almost all the tasks on time, the Git Hub Sprints system lays things out in a easy to keep track of view.  I have been having some extreme problems getting started this semester, I picked up my computer this week, so that is no longer a hardship.

Although late my sections were completed and I will work harder next week to complete my tasks and be more of a help to the team

**Comment by planetorium** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
:shipit:
