### ISSUE TITLE
Issues with pattern library set up

### ISSUE THREAD

**Issue by krystyna-Macleod** [double-double/web-app#20]
Hey Thomas, 
I'm setting up the pattern library but I got this warning when I was trying to get _bundle install_ to work. How do I fix it?
@thomasjbradley

<img width="585" alt="screen shot 2019-01-25 at 1 14 04 pm" src="https://user-images.githubusercontent.com/22229572/51764431-3310ae00-20a3-11e9-99d7-6fe78f10a80f.png">

**Comment by thomasjbradley** [comment]
Try running this command in your Terminal: `xcode-select --install`

**Comment by krystyna-Macleod** [comment]
Thank you Thomas it worked
