### ISSUE TITLE
Group review sprint 3

### ISSUE THREAD

**Issue by krystyna-Macleod** [double-double/web-app#23]
We completed setting up the pattern library and have the high fidelity wireframes for the web app.

**Comment by krystyna-Macleod** [comment]
I feel it was a good week. I had the task to set up the pattern library and Netlify. It had its challenges but was able to get through it.

**Comment by sungwoonjeong** [comment]
This week also went positive. I was able to complete mobile version of high fidelity prototype over the weekends. Sprint help me get track all the stuff that i have to complete. Only thing that i could have done over the weekend was to make it look similar to desktop version of high fidelity prototype.

**Comment by planetorium** [comment]
It was a productive week as we made decisions on what the web app will look like with mobile and desktop wireframes. I completed the desktop wireframe and got the locations and time information for all the coffee shops around campus. We kept in contact in class and on Slack and it was an overall good week.

**Comment by TamaraK** [comment]
This week went better than last week in my opinion, I was tasked with creating the map with our coffee locations and pictures of of the locations, both were completed mostly on time but we may not end up needing the photos, while communications in person went great I still need to work on staying active on the slack channel

**Comment by sungwoonjeong** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
👍
