### ISSUE TITLE
Accessing jekyll

### ISSUE THREAD

**Issue by sungwoonjeong** [double-double/web-app#38]
Hi im try to access jekyll through terminal but whenever i type 'bundle exec jekyll serve' it gives me this message 
"Traceback (most recent call last):
	1: from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
/usr/local/opt/ruby/bin/bundle:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/exe/bundle (LoadError)"

@thomasjbradley

**Comment by thomasjbradley** [comment]
Did you use `Open in Terminal` from within “GitHub Desktop”?

**Comment by sungwoonjeong** [comment]
Yes i did

**Comment by thomasjbradley** [comment]
Try deleting the `Gemfile.lock` and running `bundle install` again.

**Comment by sungwoonjeong** [comment]
Its working Now! Thank you
